### ISSUE TITLE
How to obtain lrModels?

### ISSUE THREAD

**Issue by qianlin04** [baitingzbt/PEDA#2]
Hello. I noticed that the "lrModels" in experiment.py is loaded from a pre-trained model. Is this model fitted on the "expert_uniform" dataset and used for all other types of datasets? If not, can you provide more details?

**Comment by baitingzbt** [comment]
Hi, I provided the `lrModels` fitting lines [here](https://github.com/baitingzbt/PEDA/blob/d15900c962eca2009c00dd0225f018502c2523c6/experiment.py#L160C5-L160C5).

And yes, we use "expert_uniform" lr models in all experiments, to make sure our initial rtg is not influenced by bad-performing trajectories in non-expert dataset. In practice when no expert data are available, you could also fit these lr models from the best performing trajectories under each preference. I will recommend refer to Appendix D in our paper for information.

**Comment by qianlin04** [comment]
![1](https://github.com/baitingzbt/PEDA/assets/48119752/baa6b68e-3fee-4ad5-a3b9-3dd0c509a6f8)

Thank you for your prompt reply. By the way, I would like to confirm again whether this difference in magnitude is reasonable or just a typo.

**Comment by baitingzbt** [comment]
Thanks a lot for pointing out! This a typo and scale in Table 1 should be correct.

We will update it in the next ArXiv version. I think we somehow mixed the Hypervolume vs. Sparsity scales.

**Comment by baitingzbt** [comment]
I am closing this issue for now. Feel free to discuss further by reopening.
