### ISSUE TITLE
Request for a New Download Link

### ISSUE THREAD

**Issue by Cookie-Crisp** [baitingzbt/PEDA#4]
Hi,

I’m currently using the code you provided on GitHub, but I noticed that the original download link (https://drive.google.com/file/d/19kEqdNG-ttwxmZ__30gop_KRvPf4NSjL/view) is no longer working.

Would it be possible to re-upload the checkpoint files or provide a new link? I’d really appreciate your help!

Thanks so much!

**Comment by baitingzbt** [comment]
Thanks for your continued interest! I have just updated new links, and please lmk if they work or not.

**Comment by baitingzbt** [comment]
Closing this issue.
